### PR TITLE
Allow to use any doctrine 1.y.z

### PR DESCRIPTION
**Pull request by guix77**
Hi,

I'd like to allow to use any doctrine 1.y.z.
Indeed, I'm currently using acf-builder with Themosis (https://framework.themosis.com/), which already has doctrine/ 1.3.z.

Thanks for this great package !

### CODE REVIEW

**Comment by guix77** [comment]
Huh ? The tests succeed but Scrutinizer complains about a non-commited composer.lock, which you removed a while ago.

I tried to changed composer update to composer install in CI to make Scrutinizer happy, but with no success.

Maybe see https://github.com/scrutinizer-ci/scrutinizer/issues/399

**Comment by stevep** [comment]
@guix77 Interesting. Here is the PR where it was removed https://github.com/StoutLogic/acf-builder/pull/68  it seemed to cause problems with other locks, but scrutinizer itself says it shouldn't tie a user to any specific version: https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/composer_dependencies

Although maybe with the relaxing of the version number from ~1.1 to ~1, it wouldn't cause a conflict? Is there a reason we should use ~1 as opposed to ^1.1 ?

**Comment by guix77** [comment]
Hi @stevep 

What's even more intriguing its that this .lock problem is not in the previous accepted PRs.

In fact I have to test it but ~1.1 might suffice, I think it's `"doctrine/instantiator": "~1.0.0"`that was too restrictive. With ~1 I exagerated, we don't want to accept a v2 of doctrine I guess!

Will test this and update the PR.

**Comment by guix77** [comment]
Hi Steve,

Turns out it was indeed the "doctrine/instantiator": "~1.0**.0**" that was preventing the installation with Themosis, and that ~1.0 is enough.

I also reverted the change in .travis.yml since it does not solve the Scrutinizer problem. I'm sorry, I wouldn't know too much why it complains.

I've messed up my commits my rushing too much and now there are many, would you like me to consolidate them into one or is it OK like this ?

**Comment by stevep** [comment]
I think if we do ^1.1 it should be ok and that we can even then include the composer lock file. ^1.1 should allow for 1.3 elsewhere, no? Unless I'm confusing my carrots and tildas

**Comment by guix77** [comment]
^1.1 for inflector and ^1.0 for instantiator is OK too, yes.

To commit composer.lock, intuitively I had the same assumptions as you in https://github.com/StoutLogic/acf-builder/pull/68#issuecomment-412351924

However according to https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/composer_dependencies 

> Committing the composer.lock does not tie any user of your library to a specific version.

I'm gonna try to create a project, require the versions 1.1 and then try to install my fork with the commited composer.lock.

**Comment by guix77** [comment]
All right, this is it... I had to switch to PHP 5.6 and composer install again. Damn Scrutinizer, didn't make this job as quick as I thought!

**Comment by stevep** [comment]
Thanks so much for figuring this out @guix77  I've squashed and merged it. Will release it as a patch release.

**Comment by guix77** [comment]
Thanks a lot @stevep !

**Pull request merged**
