### PR TITLE
Added addLayouts function

### PR DESCRIPTION
**Pull request by DalkMania**
Hey there. Awesome thing you have built here, very useful. I came across a scenario were I had to add an array of layouts to a builder instance. But was unable to chain the addLayout function. So I created this function. It solved my issue. Maybe others will find it useful as well.

### CODE REVIEW

**Comment by stevep** [comment]
Hey @DalkMania thanks for doing this! I haven't had a chance to check it out yet, and will be out of town this week but when I get back I'll be sure to take more of an in-depth look. (I realized there are just a couple line changes). It looks like all current tests are passing but I want to see if we can get some tests written for the new method you added.

**Comment by stevep** [comment]
Thanks @DalkMania, been going though and cleaning up, sorry this took so long. I added a test and refactored it a bit, and merged in to develop to be released to master soon. Should be in 1.9.0

**Comment by DalkMania** [comment]
Thanks @stevep. No worries. Ohh why didn't i think of that refactor :) So much simpler lol

**Comment by DalkMania** [comment]
Hey @stevep . Did this ever make it out of develop?

**Pull request merged**
