### PR TITLE
Make `getConfig` public

### PR DESCRIPTION
**Pull request by nlemoine**
- Add composer script to run test

### CODE REVIEW

**Comment by nlemoine** [comment]
There's no way to get the config of a field because method is private.

**Comment by stevep** [comment]
@nlemoine finally getting around to making updates to this library. I'm not opposed to this I don't think. At least making it `protected`, but can you give me an instance where you need it to be `public`?

Thanks!

**Comment by nlemoine** [comment]
`protected` would be useless in my case. I needed that method to be `public` so I can get informations about fields (I'm using a custom config key to know if a field must be translated/synchronized).

```php
foreach($fields->getFields() as $field) {
    $field_config = $field->getConfig();
    if( !empty($field_config['some_key'] ) {
        // Do something
    }
}
```

I found a workaround doing this:

```php
foreach($fields->getFields() as $field) {
    $field_config = $field->build();
    if( !empty($field_config['some_key'] ) {
        // Do something
    }
}
```

But having a `getConfig` method, or even better, a `getConfig($key)` method, would be much more fluent. It would make sense that `setConfig($key, $value)` also has a "reciprocity" method `getConfig($key)`.

**Comment by stevep** [comment]
I agree, I think it makes sense. I think implementing `getConfig($key)` is a great idea. I can think of some uses myself, during the build process.

**Comment by nlemoine** [comment]
Thanks for considering this 👍 

Let me know if I can help.

**Comment by nlemoine** [comment]
@stevep Any updates on this? This could really make things easier ;)

**Comment by stevep** [comment]
@nlemoine yes sorry for the delay, and delay is an understatement :)

I'll have this in a release this week.

**Comment by nlemoine** [comment]
Thanks for merging this @stevep! Will you consider `getConfig($key)` too?

**Pull request merged**
