### PR TITLE
Adding removeField and modifyField to GroupBuilder

### PR DESCRIPTION
**Pull request by voyou-sbeaulieu**
Hi! 
Keep on the good work! We use this logic for all our project now and since we use lots of group / flexible we ran into some problem with the remove / modifyField with groups.

Those functions were missing from the Group scope. linked to issue #82

### CODE REVIEW

**Comment by stevep** [comment]
Hey @voyou-sbeaulieu, finally getting around to making updates to the library. Can you add tests to the test suite for this? Just so in the future we don't break things.  Thanks

**Comment by voyou-sbeaulieu** [comment]
@stevep Sorry for the late reply! Not very familiar with the tests? But I can tell you we already made about ~5 projects with this fix and they all work well no other alteration needed.

Just tell me where / what to test and I will surely do it as soon as possible!

Thank for your time!

**Comment by marcelo2605** [comment]
@voyou-sbeaulieu Did you test this change using the latest version?

**Comment by voyou-sbeaulieu** [comment]
Hi!

So for the late delay on this ! I was on vacations.

Yes we still use this fix on the latest version I believe.

**Comment by marcelo2605** [comment]
Thanks for the reply @voyou-sbeaulieu. I added your changes on my end and try to modify a repeater subfield [this way](https://github.com/StoutLogic/acf-builder/issues/141#issue-975927131) and also [this way](https://github.com/StoutLogic/acf-builder/issues/141#issuecomment-902976148). But it still throw an error.

**Comment by stevep** [comment]
This has been released in version 1.12.0

**Pull request closed without merging**
