### PR TITLE
Add support for doctrine/inflector ^2.0

### PR DESCRIPTION
**Pull request by Log1x**
- enhance(deps): Add support for doctrine/inflector ^2.0 (backwards compatible)
- enhance(traits): Move inflector singularize to a trait
- chore(deps): Remove unused doctrine/instantiator dependency

### CODE REVIEW

**Comment by stevep** [comment]
Thanks @Log1x  this is great!

**Comment by Log1x** [comment]
I was actually just looking at this again as the test was taking forever to complete earlier – it looks like it still failed on older versions of PHP. I'd figure Composer would be smart enough to choose one of the versions compatible with the version constraint – but it is also weirdly talking about `doctrine/instantiator` in the log which from what I can tell isn't anywhere in the codebase or tests.

**Comment by stevep** [comment]
Scrutinizer is messed up, and I don't want it to handle the testing. I hadn't reconfigured Travis since they were reimplemented as a Github App. But after doing that, and fixing which linux distro to use to make sure PHP 5.4 and 5.5 still were supported, all the tests came back passing.

https://travis-ci.org/github/StoutLogic/acf-builder

Released as 1.10.0  Thanks again.

**Comment by Log1x** [comment]
Awesome. No problem!

**Pull request merged**
