### PR TITLE
Remove `composer.lock`

### PR DESCRIPTION
**Pull request by kenvunz**
Leaving `composer.lock` in the package causing composer installation issue due to `doctrine/inflector` being locked at `1.1.0` in acf-builder's `composer.lock` file, and my project already has `doctine/inflector` being locked at `1.3.0`, here is the details of the error:

```
  Problem 1
    - Installation request for doctrine/inflector (locked at v1.3.0) -> satisfiable by doctrine/inflector[v1.3.0].
    - stoutlogic/acf-builder dev-master requires doctrine/inflector ~1.1.0 -> satisfiable by doctrine/inflector[v1.1.0].
    - stoutlogic/acf-builder dev-master requires doctrine/inflector ~1.1.0 -> satisfiable by doctrine/inflector[v1.1.0].
    - Conclusion: don't install doctrine/inflector v1.1.0
    - Installation request for stoutlogic/acf-builder dev-master -> satisfiable by stoutlogic/acf-builder[dev-master].
```

### CODE REVIEW

**Comment by stevep** [comment]
@kenvunz good call, thanks

**Comment by Log1x** [comment]
I feel like the better solution to this would be to bump acf-builder's dependencies as they haven't been for a couple months.

Usually it's better practice to keep `composer.lock` VC'd [[1]](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control).

**Comment by stevep** [comment]
@Log1x I would agree with you to commit `composer.lock` if this were a project, but as a library, I'm hesitant to do so. `doctrine/inflector` 1.3 has a php 7.1 minimum requirement but I still want to support 5.6 with ACF Builder. I original made the change in the `composer.json` file here https://github.com/StoutLogic/acf-builder/commit/66b7ac3e26cef99ae82565952b991ba3c6e2fe0e

In fact @kenvunz can you confirm that removing the lock allows you to user 1.3.0? We may have to add support for multiple versions in ACF Builder's `composer.json` file

**Comment by kenvunz** [comment]
@stevep ah yip, removing `composer.lock` does the trick for me and the plugin works great with `doctrine/inflector` 1.3 too

**Pull request merged**
